// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/forge-dash/CommandRail.tsx": () => import("../components/mockups/forge-dash/CommandRail.tsx"),
  "./components/mockups/forge-dash/EditorialFeed.tsx": () => import("../components/mockups/forge-dash/EditorialFeed.tsx"),
  "./components/mockups/forge-dash/ScorecardGrid.tsx": () => import("../components/mockups/forge-dash/ScorecardGrid.tsx")
};
